add GET pagination
netascode/go-catalystcenter pull request #3
Opened 2024-02-22 14:31 UTC by jabielecki

Before this change, Client.Get could fetch max 500 items from the majority of API paths, because that's their default (and maximum) limit. Now it can transparently concatenate multiple GET calls into a single giant gjson result.

Assumption: a minority of API paths defaults to a smaller limit (e.g. 25 used by `/v2/ippools`) but a developer can force it with an explicit limit=500.

Before GET is issued, the func ensures that no writing (DELETE/POST/PUT) would run concurrently with it on the entire client (on any path - keep it simple).

With multiple GETs, the concurrency protection is uninterrupted from the first page until the last page. Protection from concurrent POST or DELETE helps against boundary items being shifted between the pages. Protection from concurrent PUT helps against items moving between pages, when sort becomes unstable due to modification of items.
Unfortunately, the protection does not cover any requests from other clients/processes/systems.

For WaitTask the protection spans until task ends, because I presume DB commit happens at the end of a task.

Known problem: presently this always leaves one goroutine for any client constructed. This requires interface change to clean that up (either cleanupFn or ctx), but I think it's unnoticeable for anyone who does not construct hundreds of client instances.

Alternative protection approaches considered before settling on this one:

1. Specify `limit=+infinity` for GET:
  - Con: not in scope of client, it's an API change.
  - Pro: no concurrency problems.

2. Shift offset by about +450 when fetching 500 items: have a margin.
  - Pro: no locking.
  - Pro: decent protection against *all* clients, not only ourselves.
  - Con: need to re-work the caller Get() interface, to explicitly include the id for elimination of duplicates. It's not only `id`, it also often uses convention `someNameId`.

2024-02-23 19:26 UTC, danischm requested changes

2024-02-23 19:26 UTC, danischm commented on client.go
> +var maxItems = 500
Should we add this as a const at the beginning?

2024-02-23 19:26 UTC, danischm commented on client.go
> +		raw, err := client.get(pathWithOffset(path, offset))
We should add the "mods" here.

2024-02-23 21:46 UTC, jabielecki commented on client.go
> +var maxItems = 500
Ah, what I want to do (next PR or this PR - as you prefer) is to change the var in the unit tests. The test output is cumbersome with 500, so I'd change to maxItems=3 there

2024-02-23 22:10 UTC, jabielecki commented on client.go
> +		raw, err := client.get(pathWithOffset(path, offset))
done

2024-02-27 20:04 UTC, danischm approved these changes

2024-02-27 20:05 UTC, merged